### ISSUE TITLE
Passing arguments via the display function?

### ISSUE THREAD

**Issue by scal0u** [TeamMaestro/nativescript-pspdfkit#10]
Thank you all for developing this.

Would there be a way to pass arguments to the display function, like:
`TNSPSPDFKit.display('~/images/file.pdf', {scrollDirection: 'vertical'});` ?

I can successfully do it via my XML element
`<TNSPSPDFView scrollDirection="vertical" scrubberBar="verticalRight" thumbnailBar="scrubber" spreadFitting="fit"></TNSPSPDFView>`
But then the fancy tools (search, bookmarks, etc) are not displayed in my ActionBar.

Thanks for any help you can provide

**Comment by triniwiz** [comment]
It is possible but not wired up , if anyone wants to know where to start check out the following

# Android 
https://github.com/TeamMaestro/nativescript-pspdfkit/blob/master/src/android/pspdfkit.ts#L80 

https://pspdfkit.com/api/android/reference/com/pspdfkit/configuration/activity/PdfActivityConfiguration.Builder.html#build()

# IOS
https://github.com/TeamMaestro/nativescript-pspdfkit/blob/master/src/ios/pspdfkit.ts#L97

https://pspdfkit.com/api/ios/Classes/PSPDFViewController.html#/c:objc(cs)PSPDFViewController(py)configuration
